/**
 * MODULE_ACTION Naming Convention
 * Sync with Backend: backend/src/constants/permissions.ts
 */
export const PERMISSIONS = {
  // Inventory Module
  INVENTORY_VIEW: "INVENTORY_VIEW",
  INVENTORY_ADD: "INVENTORY_ADD",
  INVENTORY_EDIT: "INVENTORY_EDIT",
  INVENTORY_DELETE: "INVENTORY_DELETE",
  INVENTORY_ADJUST: "INVENTORY_ADJUST",

  // Procurement Module
  PROCUREMENT_VIEW: "PROCUREMENT_VIEW",
  PROCUREMENT_CREATE: "PROCUREMENT_CREATE",
  PROCUREMENT_APPROVE: "PROCUREMENT_APPROVE",
  PROCUREMENT_RECEIVE: "PROCUREMENT_RECEIVE",

  // Partner/Vendor Management
  VENDOR_VIEW: "VENDOR_VIEW",
  VENDOR_MANAGE: "VENDOR_MANAGE",

  // Administrative & Security
  ADMIN_CONFIG: "ADMIN_CONFIG",
  USER_MANAGE: "USER_MANAGE",
  AUDIT_VIEW: "AUDIT_VIEW",
  SYSTEM_HEALTH: "SYSTEM_HEALTH"
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;
